### PR TITLE
Fix Discourse Nodes default ordering (Closes #88)

### LINKED ISSUE #88: Current version breaks Discourse Relations
@dvargas92495 

Steps to repo:
- load `https://samepage.network/releases/dvargas92495/roamjs-query-builder/`
- enable Discourse Graphs
- go to `roam/js/discourse-graph` and preview any relation

image

https://github.com/dvargas92495/roamjs-query-builder/assets/3792666/bf54a2a9-092b-4b67-93de-5e03abb1178c

### PR DESCRIPTION
**Pull request by dvargas92495**

### CODE REVIEW

File: src/utils/getDiscourseNodes.ts [hunk 1]
```diff
@@ -105,15 +102,15 @@ const getDiscourseNodes = (relations = getDiscourseRelations()) => {
...
+          source: "relation",
           canvasSettings: {},
         }))
     );
   const configuredNodeTexts = new Set(configuredNodes.map((n) => n.text));
   const defaultNodes = DEFAULT_NODES.filter(
     (n) => !configuredNodeTexts.has(n.text)
   );
-  return defaultNodes.concat(configuredNodes);
+  return configuredNodes.concat(defaultNodes);
```
Comment (dvargas92495) [inline src/utils/getDiscourseNodes.ts:113]: this is the root of the bug.

`findDiscourseNodes` iterates through the nodes to find a matching discourse node. With default ones being defined first, they were matching before configured ones.

We will need a better way to set priorities on nodes that match multiple discourse types. this works for now I think

**Review by mdroidian — APPROVED** [review]
Looks good!
